version: '3.8'

services:
  database:
    image: paudelanil9/database-app:latest
    container_name: blog-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_db
    volumes:
      - db_data:/var/lib/mysql  # Persistent volume for database storage
    networks:
      - blog-network

  backend:
    image: paudelanil9/backend-app:latest
    container_name: blog-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=blog_db
    depends_on:
      - database
    networks:
      - blog-network

  frontend:
    image: paudelanil9/frontend-app:latest
    container_name: blog-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
    
volumes:
  db_data:
