version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - chat-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/chat_db
    networks:
      - chat-network

  db:
    build: ./database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=chat_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  db-data: